version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.0
jobs:
  test:
    docker:
      - image: circleci/node:12-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Running Mocha Unit
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Create ZIP
          command: zip -x .git -r mono-to-splitwise.zip .
      - run:
          name: Deploy to AWS Lambda
          command: aws lambda update-function-code --function-name mono-to-splitwise --zip-file fileb://mono-to-splitwise.zip
workflows:
  version: 2
  aws-cli:
    jobs:
      - test
      - deploy:
          requires:
            - test